# Primarily for GaMS-27B, it was found that the model sometimes generates exceptionally short texts, which was usually
# caused by the model refusing to provide a response in line with the prompt we used. In these cases, we extracted 
# a subset of MGT that consisted only of essays that are longer than 100 words. Additionally, we also excluded 
# the essay with the"solar28" document ID, as it was found that the model produced only a repetition of the title 
# in a long loop and no additional content. The excluding of these essays was done both for MGT as well as HWT
# in order to ensure a fair comparison. By doing this, we ensured that we didn't include any model refusals 
# and repetition-type model errors. 
# 
# The same was done also for MGT generated by the gemma 2 model

import conllu
import os


def split_into_docs(sents):
    docs = list()
    curr_doc = list()
    curr_doc_id = ""
    for sent in sents:
        sent_doc_id = sent.metadata["sent_id"].strip().split(".")[0]

        if curr_doc_id == "":
            curr_doc_id = sent_doc_id
        
        if sent_doc_id != curr_doc_id:
            curr_doc_id = sent_doc_id
            docs.append(curr_doc)
            curr_doc = list()
        
        curr_doc.append(sent)
    
    docs.append(curr_doc)
    return docs


def get_short_doc_ids(docs, threshold=100):
    doc_ids = list()

    for doc in docs:
        words = 0
        doc_id = doc[0].metadata["sent_id"].strip().split(".")[0]

        for sent in doc:
            words += len(sent)
        
        if words < threshold:
            doc_ids.append(doc_id)
    
    return doc_ids


def get_final_docs(docs, short_docs_list, repetition_doc_ids, english_docs_list):
    final_docs = list()

    exclude_docs = short_docs_list + repetition_doc_ids + english_docs_list

    for doc in docs:
        if doc[0].metadata["sent_id"].strip().split(".")[0] not in exclude_docs:
            final_docs.append(doc)
    
    return final_docs


def read_file(filepath):
    with open(filepath, "r", encoding="utf-8") as rf:
        conllu_sents = conllu.parse(rf.read())
    
    return conllu_sents


def write_to_file(output_file, docs):
    if not os.path.exists(output_file):
        with open(output_file, "w", encoding="utf-8") as wf:
            for doc in docs:
                for sent in doc:
                    wf.write(sent.serialize())
    else:
        raise Exception(f"Can't write to file {output_file}, since it already exists!")



threshold = 100
gemma_english_doc_ids = ["solar864", "solar903", "solar904", "solar2781", "solar2818", "solar2949", "solar3169", 
                         "solar3374", "solar4365", "solar4398", "solar4660", "solar4840", "solar4847", "solar5021", 
                         "solar5080", "solar5133", "solar5291"]  # doc ids for Šolar where gemma-2-27b returned an essay in English instead of Slovenian
gams_english_doc_ids = ["solar1314"] # doc ids for Šolar where GaMS-27b returned an essay in English instead of Slovenian
english_doc_ids = gemma_english_doc_ids + gams_english_doc_ids
repetition_doc_ids = ["solar91"] # additionally the docs where repetition occurs

gams_input_path = os.path.join("..", "Datasets", "Solar", "Solar_GaMS-27B", "annotated", "Solar_GaMS-27B_annotated.conllu")
hwt_input_path = os.path.join("..", "Datasets", "Solar", "Solar_3.0_human", "Solar_3.0_human_relevant.conllu")
gemma_input_path = os.path.join("..", "Datasets", "Solar", "Solar_gemma-2-27B", "annotated", "Solar_gemma-2-27B_annotated.conllu")

gams_output_path = os.path.join("..", "Datasets", "Solar", "Solar_GaMS-27B", "annotated", "Solar_GaMS-27B_annotated_shorter_noeng.conllu")
hwt_output_path = os.path.join("..", "Datasets", "Solar", "Solar_3.0_human", "Solar_3.0_human_relevant_shorter_noeng.conllu")
gemma_output_path = os.path.join("..", "Datasets", "Solar", "Solar_gemma-2-27B", "annotated", "Solar_gemma-2-27B_annotated_shorter_noeng.conllu")

gams_sents = read_file(gams_input_path)
hwt_sents = read_file(hwt_input_path)
gemma_sents = read_file(gemma_input_path)

gams_docs = split_into_docs(gams_sents)
hwt_docs = split_into_docs(hwt_sents)
gemma_docs = split_into_docs(gemma_sents)

short_doc_ids = get_short_doc_ids(gams_docs, threshold=threshold)

print(f"{(len(short_doc_ids) + len(repetition_doc_ids) + len(english_doc_ids))=}")

final_gams_docs = get_final_docs(gams_docs, short_doc_ids, repetition_doc_ids, english_doc_ids)
final_hwt_docs = get_final_docs(hwt_docs, short_doc_ids, repetition_doc_ids, english_doc_ids)
final_gemma_docs = get_final_docs(gemma_docs, short_doc_ids, repetition_doc_ids, english_doc_ids)

write_to_file(gams_output_path, final_gams_docs)
write_to_file(hwt_output_path, final_hwt_docs)
write_to_file(gemma_output_path, final_gemma_docs)
